
<h1>👉 <?=$title='Card'?></h1>

<?php _code::start(); ?>
<article>
    <header>
        <h2>The white unicorn</h2>
        <h3>The purest creature ever seen</h3>
    </header>
    <img alt="Image without padding inline." src="/img/upload/unicorn_right.jpg">
    <section>
        <p>A unicorn is a mythological creature from European folklore. He is usually represented as a white horse with antelope legs, goat eyes and hair, and a horn on his forehead. In modern representations, however, it is identical to a horse, differing only in the existence of the horn.</p>

        <p>In medieval times, the horns of the unicorn were believed to have the power to neutralize poisons and were considered amulets for protection against disease. Although its existence has been the subject of debate, the unicorn continues to inspire stories of fantasy and magic, as well as an abundant production of merchandise for children today.</p>
    </section>
    <footer>
        <button type="button"><span>Action button</span></button>
        <button type="button">Hello Unicorn</button>
        <button type="submit">Buy!</button>
    </footer>
</article>
<?=_code::endWithResult('card')?>
