
<h1>👉 <?=$title='Carousel'?></h1>
   
<?php _code::start(); ?>
<div>
    <picture>
        <input type="radio" name="carousel_1" checked>
        <a href="#floating_city"><img src="/img/upload/floating_city.jpg"></a>
    </picture>

    <picture>
        <input type="radio" name="carousel_1">
        <a href="#force_of_nature"><img src="/img/upload/force_of_nature.jpg"></a>
    </picture>

    <picture>
        <input type="radio" name="carousel_1">
        <a href="#sea_wyrm"><img src="/img/upload/sea_wyrm.jpg"></a>
    </picture>
</div>
<?=_code::endWithResult('carousel')?>
