<h1>👉 <?=$title='Dialog'?></h1>

<?php _code::start(); ?>
<dialog id="dialog-1">
    <header>
        <h3>Dialog by default</h3>
        <a href="#close"><?=Ku::icon('md/close')?></a>
    </header>
    <hr>
    <section>
        Text in section tag Text in section tag Text in section tag Text in section tag Text in section tag Text in
        section tag Text in section tag…
    </section>
    <hr>
    <footer>
        <a href="#close">Cancel</a>
        <a href="#close">Accept</a>
    </footer>
</dialog>
<a href="#overlay"></a>
<a role="button" href="#dialog-1">Open by default</a>
<?=_code::endWithResult('dialog_open_by_default')?>
<hr>
<?php _code::start(); ?>
<dialog id="dialog-bottom-2">
    <header>
        <h3>Dialog from bottom</h3>
        <a href="#close"><?=Ku::icon('md/close')?></a>
    </header>
    <hr>
    <section>
        Text in section tag Text in section tag Text in section tag Text in section tag Text in section tag Text in
        section tag Text in section tag…
    </section>
    <hr>
    <footer>
        <a href="#close">Cancel</a>
        <a href="#close">Accept</a>
    </footer>
</dialog>
<a href="#overlay"></a>
<a role="button" href="#dialog-bottom-2">From bottom</a>
<?=_code::endWithResult('dialog_from_bottom')?>
<hr>
<?php _code::start(); ?>
<dialog id="dialog-left-3">
    <header>
        <h3>Dialog from left</h3>
        <a href="#close"><?=Ku::icon('md/close')?></a>
    </header>
    <hr>
    <section>
        Text in section tag Text in section tag Text in section tag Text in section tag Text in section tag Text in
        section tag Text in section tag…
    </section>
    <hr>
    <footer>
        <a href="#close">Cancel</a>
        <a href="#close">Accept</a>
    </footer>
</dialog>
<a href="#overlay"></a>
<a role="button" href="#dialog-left-3">Left</a>
<?=_code::endWithResult('dialog_left')?>
<hr>
<?php _code::start(); ?>
<dialog id="dialog-right-4">
    <header>
        <h3>Dialog from right</h3>
        <a href="#close"><?=Ku::icon('md/close')?></a>
    </header>
    <hr>
    <section>
        Text in section tag Text in section tag Text in section tag Text in section tag Text in section tag Text in
        section tag Text in section tag…
    </section>
    <hr>
    <footer>
        <a href="#close">Cancel</a>
        <a href="#close">Accept</a>
    </footer>
</dialog>
<a href="#overlay"></a>
<a role="button" href="#dialog-right-4">Right</a>
<?=_code::endWithResult('dialog_right')?>
<hr>
<?php _code::start(); ?>
<dialog id="dialog-top-5">
    <header>
        <h3>Dialog from top</h3>
        <a href="#close"><?=Ku::icon('md/close')?></a>
    </header>
    <hr>
    <section>
        Text in section tag Text in section tag Text in section tag Text in section tag Text in section tag Text in
        section tag Text in section tag…
    </section>
    <hr>
    <footer>
        <a href="#close">Cancel</a>
        <a href="#close">Accept</a>
    </footer>
</dialog>
<a href="#overlay"></a>
<a role="button" href="#dialog-top-5">Top</a>
<?=_code::endWithResult('dialog_top')?>
<hr>
<?php _code::start(); ?>
<dialog id="dialog-full-6">
    <header>
        <h3>Dialog fullscreen</h3>
        <a href="#close"><?=Ku::icon('md/close')?></a>
    </header>
    <hr>
    <section>
        Text in section tag Text in section tag Text in section tag Text in section tag Text in section tag Text in
        section tag Text in section tag…
    </section>
    <hr>
    <footer>
        <a href="#close">Cancel</a>
        <a href="#close">Accept</a>
    </footer>
</dialog>
<a role="button" href="#dialog-full-6">Fullscreen</a>
<?=_code::endWithResult('dialog_fullscreen')?>
