
<h1>👉 <?=$title='Inspiration'?></h1>

<ul>
    <li><a href="https://defensivecss.dev/" target="_blank">https://defensivecss.dev/</a></li>
    <li><a href="https://m3.material.io/" target="_blank">https://m3.material.io/</a></li>
    <li><a href="https://open-props.style/" target="_blank">https://open-props.style/</a></li>
    <li><a href="https://picnicss.com/" target="_blank">https://picnicss.com/</a></li>
    <li><a href="https://picocss.com/" target="_blank">https://picocss.com/</a></li>
    <li><a href="https://www.beercss.com/" target="_blank">https://www.beercss.com/</a></li>
</ul>

<h2>More references 👇</h2>

<ul>
    <li><a href="https://es.piliapp.com/emoji/list/" target="_blank">https://es.piliapp.com/emoji/list/</a></li>
    <li><a href="https://flutter.github.io/samples/web/material_3_demo/" target="_blank">https://flutter.github.io/samples/web/material_3_demo/</a></li>
    <li><a href="https://fonts.google.com/icons" target="_blank">https://fonts.google.com/icons</a></li>
    <li><a href="https://www.w3schools.com/tags/" target="_blank">https://www.w3schools.com/tags/</a></li>
    <li><a href="https://www.w3schools.com/w3css/" target="_blank">https://www.w3schools.com/w3css/</a></li>
</ul>
