<style>
/* img with agreed name */
div:has([name*="carousel-"])~* {
    display: none;
}

/* input as a button to show the img or link associated */
div:has([name*="carousel-"]:nth-of-type(1):checked)~*:nth-of-type(1),
div:has([name*="carousel-"]:nth-of-type(2):checked)~*:nth-of-type(2),
div:has([name*="carousel-"]:nth-of-type(3):checked)~*:nth-of-type(3),
div:has([name*="carousel-"]:nth-of-type(4):checked)~*:nth-of-type(4),
div:has([name*="carousel-"]:nth-of-type(5):checked)~*:nth-of-type(5),
div:has([name*="carousel-"]:nth-of-type(6):checked)~*:nth-of-type(6),
div:has([name*="carousel-"]:nth-of-type(7):checked)~*:nth-of-type(7),
div:has([name*="carousel-"]:nth-of-type(8):checked)~*:nth-of-type(8) {
    display: block;
}

/* picture or other tag as container */
*:has(>div>[name*="carousel-"]) {
    position: relative;
}

/* div with agreed name */
div:has(>[name*="carousel-"]) {
    mix-blend-mode: difference;
    position: absolute;
    bottom: 8px;
    left: 50%;
    transform: translateX(-50%);
}
</style>

<h1>Carousel</h1>
   
<picture>
    <div>
        <input type="radio" name="carousel-1" checked>
        <input type="radio" name="carousel-1">
        <input type="radio" name="carousel-1">
    </div>
    <a href="#floating_city"><img src="/img/upload/floating_city.jpg"></a>
    <a href="#force_of_nature"><img src="/img/upload/force_of_nature.jpg"></a>
    <a href="#sea_wyrm"><img src="/img/upload/sea_wyrm.jpg"></a>
</picture>
